# This is a basic workflow to help you get started with Actions

name: Update Content

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, testing ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Automatically trigger the import. 20:30 JST == 11:30 UTC
  # https://www.timeanddate.com/worldclock/converter.html?iso=20210829T113000&p1=248&p2=1440
  schedule:
    - cron: '30 11 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Confluence Integration

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      # Fetch and process the content from the backend
      # TODO: Implement.
      # Runs a set of commands using the runners shell
      - name: Trigger Import from the backend. and Prepare a commit.
        run: |
          mkdir -p cache _confluence_pages
          bash ./tools/run.sh
          git diff
          find .
          git config --global user.name "by github-actions"
          git config --global user.email "on-behalf-of-haruki@users.noreply.github.com"
          git add _confluence_pages c_attachments/
          git commit -m "Imported at $(date)"
        env:
          CONFLUENCE_TOKEN: ${{ secrets.CONFLUENCE_TOKEN }}

      # We might need it to implement incremental build.
      - uses: actions/upload-artifact@v2
        with:
          name: last-run-state
          path: |
            _site
            cache
            processing.log

      # Create a pull-request and push to gh-pages. Maybe only on scheduled and manual triggered.
      # TODO: Implement.
      - name: Push to gh-pages
        if: ${{ github.ref == 'refs/heads/main' }} # Only in the execution from the main.
        run: |
          git push origin

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.ref == 'refs/heads/testing' }} && ${{ failure() }} # Only in the execution from the testing.
        with:
          limit-access-to-actor: true
